[debug] [2024-01-19T00:18:29.131Z] ----------------------------------------------------------------------
[debug] [2024-01-19T00:18:29.138Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\SSAFY\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js login
[debug] [2024-01-19T00:18:29.138Z] CLI Version:   13.0.3
[debug] [2024-01-19T00:18:29.138Z] Platform:      win32
[debug] [2024-01-19T00:18:29.138Z] Node Version:  v20.10.0
[debug] [2024-01-19T00:18:29.138Z] Time:          Fri Jan 19 2024 09:18:29 GMT+0900 (대한민국 표준시)
[debug] [2024-01-19T00:18:29.138Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-01-19T00:18:29.141Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[info] Already logged in as youngjoo000108@gmail.com
[debug] [2024-01-19T00:18:33.616Z] <<< [apiv2][status] GET https://firebase-public.firebaseio.com/cli.json 200
[debug] [2024-01-19T00:18:33.617Z] <<< [apiv2][body] GET https://firebase-public.firebaseio.com/cli.json {"cloudBuildErrorAfter":1594252800000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390400000,"node8RuntimeDisabledAfter":1615809600000,"node8WarnAfter":1600128000000}
[debug] [2024-01-19T00:18:35.067Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\SSAFY\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:258:49)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
[error] 
[error] Error: An unexpected error has occurred.
